config/routes.rb
Rails.application.routes.draw do
  # resources :posts
  resources :dashes do
    resources :posts
  end

  root 'dashes#index'
end

app/models/dash.rb
class Dash < ActiveRecord::Base
	has_many :posts	




	def giph(terms)
		url = "http://api.giphy.com/v1/gifs/search?q="+terms+"&api_key=dc6zaTOxFJmzC&limit=50"
		resp = Net::HTTP.get_response(URI.parse(url))
		buffer = resp.body
		result = JSON.parse(buffer)
		temp = []
			result['data'].each do |x|
				temp.push(x["images"]["fixed_height"]["url"], x["url"], x["images"]["downsized_still"]["url"])
			end
		return temp 
	end

	def twit(search)
		twitCli = Twitter::REST::Client.new do |config|
		  config.consumer_key        = "KxGET2RtfQlVM6oDOAZFXirkJ"
		  config.consumer_secret     = "R2mwQWpMz3SXqBUQsoTnlMhwP2JPhxTbJRaGjJ1rfAHlXd8P0D"
		  config.access_token        = "28226407-kH0D7UDHDobk93OaHXMcuLlAwpNogkjROlNB20DGo"
		  config.access_token_secret = "ID3kizlxpu3JU3yGKSNaxUZtWAhUivLA6haguOfHq1mqO"
		end

		temp = []
		twitCli.search(search.to_s + " -rt").take(15).collect do |tweet|
			temp.push(["@"+tweet.user.screen_name, tweet.text])
		end



		return temp
	end

	def redd(search)


		redd_url = "https://www.reddit.com/subreddits/search.json?q=" + search
		resp = Net::HTTP.get_response(URI.parse(redd_url))
		data = resp.body
		search_res = JSON.parse(data)		
		temp = []
		search_res["data"]["children"].each do |subredd|
			temp.push(subredd)
		end

		return temp


		# reddit_api_url = "https://www.reddit.com/r/"+subreddit+"/.json"



		# resp = Net::HTTP.get_response(URI.parse(reddit_api_url))
		# data = resp.body
		# result = JSON.parse(data)
		# temp = []
		# result["data"]["children"].each do |post|
		# 	temp.push(post["data"]["preview"]["images"].first["source"])
		# end
		# return temp.collect{|x|x["url"]}
	end


	def randomize
		temp = []
		temp = self.twit + self.giph("cat+asshole") + self.redd("catsareassholes")
		return temp.shuffle
	end





end

app/models/post.rb
class Post < ActiveRecord::Base
	has_one :dash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashes_controller.rb
class DashesController < ApplicationController
  before_action :set_dash, only: [:show, :edit, :update, :destroy]

  # GET /dashes
  # GET /dashes.json
  def index
    @dashes = Dash.all
  end

  # GET /dashes/1
  # GET /dashes/1.json
  def show
  end

  # GET /dashes/new
  def new
    @dash = Dash.new
  end

  # GET /dashes/1/edit
  def edit
  end

  # POST /dashes
  # POST /dashes.json
  def create
    @dash = Dash.new(dash_params)

    respond_to do |format|
      if @dash.save
        format.html { redirect_to @dash, notice: 'Dash was successfully created.' }
        format.json { render :show, status: :created, location: @dash }
      else
        format.html { render :new }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashes/1
  # PATCH/PUT /dashes/1.json
  def update
    respond_to do |format|
      if @dash.update(dash_params)
        format.html { redirect_to @dash, notice: 'Dash was successfully updated.' }
        format.json { render :show, status: :ok, location: @dash }
      else
        format.html { render :edit }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashes/1
  # DELETE /dashes/1.json
  def destroy
    @dash.destroy
    respond_to do |format|
      format.html { redirect_to dashes_url, notice: 'Dash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dash
      @dash = Dash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dash_params
      params.require(:dash).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :og_source, :body, :image_src)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashes_helper.rb
module DashesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashes/_form.html.erb
<%= form_for(@dash) do |f| %>
  <% if @dash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dash.errors.count, "error") %> prohibited this dash from being saved:</h2>

      <ul>
      <% @dash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashes/edit.html.erb
<h1>Editing Dash</h1>

<%= render 'form' %>

<%= link_to 'Show', @dash %> |
<%= link_to 'Back', dashes_path %>

app/views/dashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dashes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashes.each do |dash| %>
      <tr>
        <td><%= dash.title %></td>
        <td><%= link_to 'Show', dash %></td>
        <td><%= link_to 'Edit', edit_dash_path(dash) %></td>
        <td><%= link_to 'Destroy', dash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dash', new_dash_path %>

app/views/dashes/new.html.erb
<h1>New Dash</h1>

<%= render 'form' %>

<%= link_to 'Back', dashes_path %>

app/views/dashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dash.title %>
</p>

<%= link_to 'Edit', edit_dash_path(@dash) %> |
<%= link_to 'Back', dashes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cfams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :og_source %><br>
    <%= f.text_field :og_source %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image_src %><br>
    <%= f.text_field :image_src %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Og source</th>
      <th>Body</th>
      <th>Image src</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.og_source %></td>
        <td><%= post.body %></td>
        <td><%= post.image_src %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Og source:</strong>
  <%= @post.og_source %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Image src:</strong>
  <%= @post.image_src %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>